name: 'Generate Warp Changelog'
description: 'Generates a Warp changelog for a given version and relase channel'
author: 'warpdotdev'
inputs:
  github_auth_token: # change this
    required: true
    description: 'input description here'  
runs:
  using: 'node16'
  main: 'dist/index.js'
